
// points
POINTS_SUPPLY_CRATE				= 5;
POINTS_SUPPLY_CRATE_FIRST		= 15;
POINTS_RING						= 10;
POINTS_RING_FIRST				= 30;
POINTS_CUP						= 20;
POINTS_CUP_FIRST				= 60;
POINTS_CUP_LEAST_STROKES		= 60;
POINTS_OOB						= -10;

// distances
FOLIAGE_DISTANCE_MIN			= 4096;
FOLIAGE_DISTANCE_MAX			= 5120;
FOLIAGE_DISTANCE_MIN_SQR		= FOLIAGE_DISTANCE_MIN * FOLIAGE_DISTANCE_MIN;
FOLIAGE_DISTANCE_MAX_SQR		= FOLIAGE_DISTANCE_MAX * FOLIAGE_DISTANCE_MAX;
FOLIAGE_FADE_DISTANCE_SQR_INV	= 1 / ( FOLIAGE_DISTANCE_MAX_SQR - FOLIAGE_DISTANCE_MIN_SQR );

// stuff
ROCKET_SPEED					= 2000;
HOMING_ROCKET_SPEED				= 750;
HOMING_TARGET_RADIUS			= 128;
MAGNET_ATTRACT_RADIUS			= 256;
MAGNET_ATTRACT_STRENGTH			= 0.1;
MAGNET_DURATION					= 30;
BOT_STROKE_STRENGTH				= 150;
